# Module 7: Using array operations instead of loops 

In [1]:
import numpy as np

## Example: midpoint calculation 

Find the midpoints

$$
m_i = \frac{1}{2} (a_i + a_{i+1}); \quad 0 \le i < N-1
$$

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

### Explicit Python loop 

In [3]:
N = len(a)
m = np.zeros(N-1)
for i in range(N-1):
    m[i] = 0.5*(a[i] + a[i+1])

In [4]:
m

array([0.5, 1.5, 2.5, 3.5, 4.5])

### Can we avoid the loop?

* `a[i]` covers the elements `[0, 1, 2, 3, 4]`
* `a[i+1]` covers the elements `[1, 2, 3, 4, 5]`

Think about shifting the arrays:
```
[0 1 2 3 4 5]
  [0 1 2 3 4 5]
-------------
   1 3 5 7 9
                   * 0.5
========================
  0.5 1.5 2.5 3.5 4.5 
```    

Can we get these numbers by slicing?

```
  [1 2 3 4 5]  = a[1:]
  [0 1 2 3 4]  = a[:-1]
-------------    ---------------
   1 3 5 7 9   = a[1:] + a[:-1]
```   

Think about these equivalences between loop and array approach:

* `a[i]` is like `a[:-1]`
* `a[i+1]` is like `a[1:]`

### Use the sliced arrays

In [5]:
m = 0.5*(a[:-1] + a[1:])
m

array([0.5, 1.5, 2.5, 3.5, 4.5])

```
[0, 1, 2, 3, 4, 5]
   [0, 1, 2, 3, 4, 5]
---------------------    
+  [1, 3, 5, 7, 9]
```

Using sliced arrays is
* more readable (more elegant)
* faster 

**Prefered way to work with arrays**

### Speed-up

In [6]:
%%timeit
m = np.zeros(N)
for i in range(N-1):
    m[i] = 0.5*(a[i] + a[i+1])

16.5 µs ± 451 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%%timeit
m = 0.5*(a[:-1] + a[1:])

2.35 µs ± 52.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**Speed-ups for bigger problems can be 100-1000 fold!**

## Summary

* avoid Python loops
* use numpy array operations
* thinking about array shifting can become mind-bending but *always worth the effort*